from __future__ import annotations

import os
from typing import AsyncIterator, Dict

import asyncpg
import pytest
import pytest_asyncio

from .sdk import AgentMarketSDK
from .utils import new_uuid, unique_agent_name, unique_email

DEFAULT_PASSWORD = "Testing123!"


@pytest_asyncio.fixture
async def agentmarket_sdk() -> AsyncIterator[AgentMarketSDK]:
    sdk = AgentMarketSDK()
    try:
        yield sdk
    finally:
        await sdk.close()


async def _persist_user_in_db(user_id: str, email: str, display_name: str) -> None:
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        pytest.skip("DATABASE_URL is required for integration tests")

    conn = await asyncpg.connect(dsn=database_url)
    try:
        await conn.execute(
            'INSERT INTO "User"(id, email, "displayName", password) VALUES($1, $2, $3, $4) '
            'ON CONFLICT (id) DO NOTHING',
            user_id,
            email,
            display_name,
            "placeholder-hash",
        )
    finally:
        await conn.close()


@pytest_asyncio.fixture
async def registered_user(agentmarket_sdk: AgentMarketSDK) -> Dict[str, str]:
    email = unique_email()
    display_name = f"QA Creator {email.split('@')[0][-4:]}"
    response = await agentmarket_sdk.register_user(
        email=email,
        display_name=display_name,
        password=DEFAULT_PASSWORD,
    )
    user = response["user"]
    await _persist_user_in_db(user["id"], user["email"], user["displayName"])
    return {
        "id": user["id"],
        "email": user["email"],
        "displayName": user["displayName"],
        "password": DEFAULT_PASSWORD,
    }


@pytest_asyncio.fixture
async def reviewer_user(agentmarket_sdk: AgentMarketSDK) -> Dict[str, str]:
    email = unique_email("reviewers.test")
    display_name = f"QA Reviewer {email.split('@')[0][-4:]}"
    response = await agentmarket_sdk.register_user(
        email=email,
        display_name=display_name,
        password=DEFAULT_PASSWORD,
    )
    user = response["user"]
    await _persist_user_in_db(user["id"], user["email"], user["displayName"])
    return {
        "id": user["id"],
        "email": user["email"],
        "displayName": user["displayName"],
        "password": DEFAULT_PASSWORD,
    }


@pytest.fixture
def sample_agent_payload(registered_user: Dict[str, str]) -> Dict[str, object]:
    return {
        "name": unique_agent_name(),
        "description": "Autogenerated agent for lifecycle tests validating CRUD and execution paths.",
        "categories": ["qa", "integration"],
        "tags": ["python", "autogen"],
        "pricingModel": "subscription",
        "visibility": "PUBLIC",
        "creatorId": registered_user["id"],
    }


@pytest.fixture
def execution_payload(reviewer_user: Dict[str, str]) -> Dict[str, object]:
    return {
        "initiatorId": reviewer_user["id"],
        "input": '{"task": "demo run"}',
        "jobReference": f"job-{new_uuid()}",
        "budget": 12.34,
    }


@pytest.fixture
def review_payload(reviewer_user: Dict[str, str]) -> Dict[str, object]:
    return {
        "reviewerId": reviewer_user["id"],
        "reviewStatus": "APPROVED",
        "targetStatus": "APPROVED",
        "notes": "Looks ready for production.",
    }


@pytest.fixture
def submission_payload(reviewer_user: Dict[str, str]) -> Dict[str, object]:
    return {
        "reviewerId": reviewer_user["id"],
        "notes": "Please validate business logic.",
    }
from __future__ import annotations

import os
from typing import AsyncIterator, Dict

import asyncpg
import pytest
import pytest_asyncio

from .sdk import AgentMarketSDK
from .utils import new_uuid, unique_agent_name, unique_email

DEFAULT_PASSWORD = "Testing123!"


@pytest_asyncio.fixture
async def agentmarket_sdk() -> AsyncIterator[AgentMarketSDK]:
    sdk = AgentMarketSDK()
    try:
        yield sdk
    finally:
        await sdk.close()


async def _persist_user_in_db(user_id: str, email: str, display_name: str) -> None:
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        pytest.skip("DATABASE_URL is required for integration tests")

    conn = await asyncpg.connect(dsn=database_url)
    try:
        await conn.execute(
            'INSERT INTO "User"(id, email, "displayName", password) VALUES($1, $2, $3, $4) '
            'ON CONFLICT (id) DO NOTHING',
            user_id,
            email,
            display_name,
            "placeholder-hash",
        )
    finally:
        await conn.close()


@pytest_asyncio.fixture
async def registered_user(agentmarket_sdk: AgentMarketSDK) -> Dict[str, str]:
    email = unique_email()
    display_name = f"QA Creator {email.split('@')[0][-4:]}"
    response = await agentmarket_sdk.register_user(
        email=email,
        display_name=display_name,
        password=DEFAULT_PASSWORD,
    )
    user = response["user"]
    await _persist_user_in_db(user["id"], user["email"], user["displayName"])
    return {
        "id": user["id"],
        "email": user["email"],
        "displayName": user["displayName"],
        "password": DEFAULT_PASSWORD,
    }


@pytest_asyncio.fixture
async def reviewer_user(agentmarket_sdk: AgentMarketSDK) -> Dict[str, str]:
    email = unique_email("reviewers.test")
    display_name = f"QA Reviewer {email.split('@')[0][-4:]}"
    response = await agentmarket_sdk.register_user(
        email=email,
        display_name=display_name,
        password=DEFAULT_PASSWORD,
    )
    user = response["user"]
    await _persist_user_in_db(user["id"], user["email"], user["displayName"])
    return {
        "id": user["id"],
        "email": user["email"],
        "displayName": user["displayName"],
        "password": DEFAULT_PASSWORD,
    }


@pytest.fixture
def sample_agent_payload(registered_user: Dict[str, object]) -> Dict[str, object]:
    return {
        "name": unique_agent_name(),
        "description": "Autogenerated agent for lifecycle tests validating CRUD and execution paths.",
        "categories": ["qa", "integration"],
        "tags": ["python", "autogen"],
        "pricingModel": "subscription",
        "visibility": "PUBLIC",
        "creatorId": registered_user["id"],
    }


@pytest.fixture
def execution_payload(reviewer_user: Dict[str, object]) -> Dict[str, object]:
    return {
        "initiatorId": reviewer_user["id"],
        "input": '{"task": "demo run"}',
        "jobReference": f"job-{new_uuid()}",
        "budget": 12.34,
    }


@pytest.fixture
def review_payload(reviewer_user: Dict[str, object]) -> Dict[str, object]:
    return {
        "reviewerId": reviewer_user["id"],
        "reviewStatus": "APPROVED",
        "targetStatus": "APPROVED",
        "notes": "Looks ready for production.",
    }


@pytest.fixture
def submission_payload(reviewer_user: Dict[str, object]) -> Dict[str, object]:
    return {
        "reviewerId": reviewer_user["id"],
        "notes": "Please validate business logic.",
    }
